#!/bin/bash
set -euo pipefail

# Sync Terraform configuration from SSM Parameter Store
# Usage: ./scripts/sync-terraform-config.sh <staging|prod>
#
# SSM is the source of truth for environment-specific values.
# This prevents committing sensitive or org-specific values to the public repo.
#
# SSM Parameters (per environment):
#   /treasury-home/terraform-config/{env}/environment        - "staging" or "prod"
#   /treasury-home/terraform-config/{env}/domain_name        - Custom domain
#   /treasury-home/terraform-config/{env}/route53_zone_name  - Route53 zone name
#
# To set up a new environment, create the SSM parameters first:
#   aws ssm put-parameter --name /treasury-home/terraform-config/prod/environment --value prod --type String
#
# IMPORTANT: Do not edit terraform.tfvars directly - it's auto-generated.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

# Parse environment argument
ENV="${1:-}"
if [[ ! "$ENV" =~ ^(staging|prod)$ ]]; then
  echo "Usage: $0 <staging|prod>"
  echo ""
  echo "Examples:"
  echo "  $0 staging   # Sync staging environment config"
  echo "  $0 prod      # Sync prod environment config"
  exit 1
fi

SSM_PREFIX="/treasury-home/terraform-config/${ENV}"
TFVARS_FILE="$PROJECT_ROOT/terraform/terraform.tfvars"

echo "Syncing Terraform config for $ENV from SSM..."
echo ""

# Fetch all terraform-config parameters for this environment
ENVIRONMENT=$(aws ssm get-parameter --name "$SSM_PREFIX/environment" --query 'Parameter.Value' --output text 2>/dev/null || echo "")
DOMAIN_NAME=$(aws ssm get-parameter --name "$SSM_PREFIX/domain_name" --query 'Parameter.Value' --output text 2>/dev/null || echo "")
ROUTE53_ZONE_NAME=$(aws ssm get-parameter --name "$SSM_PREFIX/route53_zone_name" --query 'Parameter.Value' --output text 2>/dev/null || echo "")

# Validate required values exist
if [ -z "$ENVIRONMENT" ]; then
  echo "ERROR: SSM parameter $SSM_PREFIX/environment not found"
  echo ""
  echo "Create it with:"
  echo "  aws ssm put-parameter --name $SSM_PREFIX/environment --value $ENV --type String"
  exit 1
fi

# Generate terraform.tfvars
cat > "$TFVARS_FILE" << EOF
# Auto-generated from SSM Parameter Store
# Source: $SSM_PREFIX/*
# Generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
#
# DO NOT EDIT THIS FILE DIRECTLY
# Update SSM parameters and re-run: ./scripts/sync-terraform-config.sh $ENV

environment = "$ENVIRONMENT"
EOF

# Add optional parameters if they exist
if [ -n "$DOMAIN_NAME" ]; then
  echo "domain_name = \"$DOMAIN_NAME\"" >> "$TFVARS_FILE"
fi

if [ -n "$ROUTE53_ZONE_NAME" ]; then
  echo "route53_zone_name = \"$ROUTE53_ZONE_NAME\"" >> "$TFVARS_FILE"
fi

echo "Generated $TFVARS_FILE:"
echo "─────────────────────────────────────"
cat "$TFVARS_FILE"
echo "─────────────────────────────────────"
echo ""
echo "✓ Terraform config for $ENV synced from SSM"
echo ""

# Select appropriate terraform workspace
WORKSPACE="default"
if [ "$ENV" = "prod" ]; then
  WORKSPACE="prod"
fi

cd "$PROJECT_ROOT/terraform"
if terraform workspace select "$WORKSPACE" 2>/dev/null; then
  echo "✓ Switched to terraform workspace: $WORKSPACE"
else
  echo "Note: Run 'terraform workspace new $WORKSPACE' if workspace doesn't exist"
fi
cd - > /dev/null

echo ""
echo "Next steps:"
echo "  cd terraform && terraform plan"
